### ISSUE TITLE
pangolin --add-assignment-cache fails with "NameError: name 'CalledProcessError' is not defined"

### ISSUE THREAD

**Issue by GorgonVZ** [cov-lineages/pangolin-data#10]
Dear pangos,
I just tried to install the assignment cache using, but I get the Error Message pasted to the very end of this message.
Can you give me any advice how to solve this? Am I running a misscompiled installation? 

Command I used:
 conda activate pangolin
/home/pcr/anaconda3/envs/pangolin/bin/pangolin --add-assignment-cache

Versions I use:
pangolin already latest release (v4.0.6)
pangolin-data already latest release (v1.8)
constellations already latest release (v0.1.10)
scorpio already latest release (v0.3.17)
pangolin-data already latest release (v1.8)
constellations already latest release (v0.1.10)
UShER (v0.5.4)

I am mostly interested in the "add-assignment-cache" feature, because I would like to have acccess to the most "up to date" usher tree.
This brings me to my question/feature request...
 Is it possible to update the pangolin_data repository more regularly than this is the case right now? Actually 15 days are a quite long timeperiod if one tries to find the most recent viral-lineages around.

Thanks in advance and for the amazing work you are doing! You are awsome!  

##################################################################################
/home/pcr/anaconda3/envs/pangolin/bin/pangolin --add-assignment-cache
Traceback (most recent call last):
  File "/home/pcr/anaconda3/envs/pangolin/lib/python3.7/site-packages/pangolin/utils/update.py", line 82, in install_pangolin_assignment
    import pangolin_assignment
ModuleNotFoundError: No module named 'pangolin_assignment'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pcr/anaconda3/envs/pangolin/lib/python3.7/site-packages/pangolin/utils/update.py", line 61, in git_lfs_install
    stderr=subprocess.DEVNULL)
  File "/home/pcr/anaconda3/envs/pangolin/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/pcr/anaconda3/envs/pangolin/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/pcr/anaconda3/envs/pangolin/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git-lfs': 'git-lfs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pcr/anaconda3/envs/pangolin/bin/pangolin", line 8, in <module>
    sys.exit(main())
  File "/home/pcr/anaconda3/envs/pangolin/lib/python3.7/site-packages/pangolin/command.py", line 113, in main
    update.install_pangolin_assignment()
  File "/home/pcr/anaconda3/envs/pangolin/lib/python3.7/site-packages/pangolin/utils/update.py", line 86, in install_pangolin_assignment
    git_lfs_install()
  File "/home/pcr/anaconda3/envs/pangolin/lib/python3.7/site-packages/pangolin/utils/update.py", line 62, in git_lfs_install
    except CalledProcessError as e:
NameError: name 'CalledProcessError' is not defined
################################################################################################

**Comment by GorgonVZ** [comment]
Hi @AngieHinrichs,
thanks that solved my issue!
Nevertheless, do you think it's feasible to update usher's reference-tree in shorter time intervals to, be more up to date? 
Thanks,
GVZ

**Comment by AngieHinrichs** [comment]
Hi @GorgonVZ -- yes, it has been a few weeks.  I'm hoping there will be another [release](https://github.com/cov-lineages/pango-designation/releases) of pango-designation by the end of this week, and then @aineniamh and I can update pangolin-data with the new release.
